# Generated by Django 5.2.7 on 2025-10-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands"},
        ),
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="Description yay"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(verbose_name="Image url"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Price"
            ),
        ),
    ]
