# Generated by Django 5.2.7 on 2025-10-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_brand_options_alter_brand_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.category",
            ),
        ),
    ]
